const countries = [
  "France",
  "United Kingdom",
  "Spain",
  "Portugal",
  "Austria",
  "Prussia",
  "Russia",
  "Ottoman Empire",
  "Sweden",
  "Denmark-Norway",
  "Switzerland",
  "Kingdom of Italy",
  "Kingdom of Naples",
  "Kingdom of Sicily",
  "Papal States",
  "Kingdom of Sardinia",
  "Dutch Republic",
  "Batavian Republic",
  "Kingdom of Holland",
  "Belgium",
  "Luxembourg",
  "Poland (Duchy of Warsaw)",
  "Grand Duchy of Warsaw",
  "Confederation of the Rhine",
  "Bavaria",
  "Saxony",
  "Württemberg",
  "Baden",
  "Hanover",
  "Westphalia",
  "Genoa",
  "Venice",
  "Parma",
  "Modena",
  "Tuscany",
  "Dalmatia",
  "Illyrian Provinces",
  "Transylvania",
  "Wallachia",
  "Moldavia",
  "Serbia",
  "Croatia",
  "Slovenia",
  "Hungary",
  "Bohemia",
  "Moravia",
  "Galicia",
  "Finland",
  "Norway",
  "Ireland",
  "Scotland",
  "Wales"
];
